// Tính năng trang SP không phải thuốc
const PRODUCT_ADD = "product_add";
const PRODUCT_EDIT = "product_edit";
const PRODUCT_STOP_BUSINESS = "product_stop_business";
const PRODUCT_EXPORT = "product_export";
const PRODUCT_IMPORT = "product_import";
const PRODUCT_PRINT = "product_print";
const PRODUCT_LIST = "product_list";

export const PERMISSION_PRODUCT_GENERAL = {
  PRODUCT_ADD: PRODUCT_ADD,
  PRODUCT_EDIT: PRODUCT_EDIT,
  PRODUCT_STOP_BUSINESS: PRODUCT_STOP_BUSINESS,
  PRODUCT_EXPORT: PRODUCT_EXPORT,
  PRODUCT_IMPORT: PRODUCT_IMPORT,
  PRODUCT_PRINT: PRODUCT_PRINT,
  PRODUCT_LIST: PRODUCT_LIST,
};

const PRODUCT_GROUP_EDIT = "product_group_edit";
const PRODUCT_GROUP_DELETE = "product_group_delete";
const PRODUCT_GROUP_ADD = "product_group_add";
const PRODUCT_GROUP_LIST = "product_group_list";
const PRODUCT_GROUP_EXPORT = "product_group_export";

export const PERMISSION_PRODUCT_GROUP = {
  PRODUCT_GROUP_EDIT: PRODUCT_GROUP_EDIT,
  PRODUCT_GROUP_DELETE: PRODUCT_GROUP_DELETE,
  PRODUCT_GROUP_ADD: PRODUCT_GROUP_ADD,
  PRODUCT_GROUP_LIST: PRODUCT_GROUP_LIST,
  PRODUCT_GROUP_EXPORT: PRODUCT_GROUP_EXPORT,
};

const PRODUCT_CATEGORY_EDIT = "product_category_edit";
const PRODUCT_CATEGORY_DELETE = "product_category_delete";
const PRODUCT_CATEGORY_ADD = "product_category_add";
const PRODUCT_CATEGORY_LIST = "product_category_list";
const PRODUCT_CATEGORY_EXPORT = "product_category_export";

export const PERMISSION_PRODUCT_CATEGORY = {
  PRODUCT_CATEGORY_EDIT: PRODUCT_CATEGORY_EDIT,
  PRODUCT_CATEGORY_DELETE: PRODUCT_CATEGORY_DELETE,
  PRODUCT_CATEGORY_ADD: PRODUCT_CATEGORY_ADD,
  PRODUCT_CATEGORY_LIST: PRODUCT_CATEGORY_LIST,
  PRODUCT_CATEGORY_EXPORT: PRODUCT_CATEGORY_EXPORT,
};

export const PERMISSION_PRODUCT = {
  ...PERMISSION_PRODUCT_GENERAL,
  ...PERMISSION_PRODUCT_GROUP,
  ...PERMISSION_PRODUCT_CATEGORY,
};
